ALTER TABLE "Sale"
ADD COLUMN "paymentCashAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "paymentCardAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "paymentTransferAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
